#!/usr/bin/env ruby

require_relative '../lib/transfer-worker'

activity_arn = ENV['ACTIVITY_ARN']
aws_region = ENV['AWS_REGION']

unless aws_region
  begin
    ec2_metadata = Aws::EC2Metadata.new
    aws_region = ec2_metadata.get('/latest/meta-data/placement/region')
    ENV['AWS_REGION'] = aws_region
  rescue StandardError => e
    puts "Unable to get ec2 metadata. #{e.message}"
  end
end
aws_region ||= 'us-east-1'

worker_name = ENV['TRANSFER_WORKER_NAME'] || `hostname` || 'envoi-transfer-worker'

states_client_args = {
  region: aws_region
}
tw = TransferWorker.new({
                          states_client_args:,
                          worker_name:
                        })
tw.run(activity_arn)
